### ISSUE TITLE
Deno 2 app support

### ISSUE THREAD

**Issue by aaronpowell** [CommunityToolkit/Aspire#109]
### .NET Aspire issue link

https://github.com/dotnet/aspire/issues/5467

### Overview

[Deno](https://deno.com/) is a JavaScript server runtime that has been gaining popularity as an alternative to Node.js due to its all-in-one approach to tooling and native TypeScript support.

Given there's already support for Node.js apps, we should have Deno as an option for people who wish to use that instead. We should only focus on Deno 2 though for simplicity.

### Usage example

```csharp
var api = builder.AddDenoApp("deno-api", "../api");
```

Where applicable, the configuration options available with `AddNodeApp` should be mapped to `AddDenoApp`.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by brian-guerrero** [comment]
I'm interested in working on this issue, but I see it's okay for it to be assigned to you @aaronpowell. Is it alright with you if I give it a shot?

**Comment by aaronpowell** [comment]
Go for it @brian-guerrero 

It only says that in the issue body because it's defaulted to that and I created the issue 🤣

**Comment by aaronpowell** [comment]
Thanks for the contribution @brian-guerrero, we'll get this shipped soon (it might not be until the Aspire 9 release though). In the interim you can use the integration from the Azure Artifacts feed.
