### ISSUE TITLE
AddModel on Ollama not downloading

### ISSUE THREAD

**Issue by Mrxx99** [CommunityToolkit/Aspire#118]
### Describe the bug

Adding two models to Ollama where the second one is a substring of the other does prevent the second one from downloading because to this check:
```csharp
var localModels = await ollamaClient.ListLocalModels(cancellationToken);
return localModels.Any(m => m.Name.StartsWith(model));
```

This can also happen when using a data valume and then changing the model to or adding a new one which is a substring of an already downloaded one

### Steps to reproduce

```csharp
var ollama = builder.AddOllama("ollama", port: null)
    .WithDataVolume()
    .AddModel("phi3")
    .AddModel("phi");
```

### Expected behavior

Determining if a model is downloaded should now rely on substring matching

### IDE and version

VS 2022 Preview

### Nuget packages

- [ ] Aspire.CommunityToolkit.Hosting.Azure.StaticWebApps
- [ ] Aspire.CommunityToolkit.Hosting.Java
- [ ] Aspire.CommunityToolkit.Hosting.NodeJS.Extensions
- [x] Aspire.CommunityToolkit.Hosting.Ollama

### Nuget package version(s)

current git

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
Good catch!
