### ISSUE TITLE
Allow specifying selected model when calling WithReference with a Ollama resource

### ISSUE THREAD

**Issue by Mrxx99** [CommunityToolkit/Aspire#119]
### Related to an existing integration?

Yes

### Existing integration

Aspire.CommunityToolkit.Hosting.Ollama

### Overview

Allow specifying selected model when using WithReference with a Ollama resource.
Currently the selected model can only be easily set by using WithDefaultModel, but that locks to only one model and can't reference different ones in different resources easily. This can easily be solved by having an optional parameter on the custom WithReference for Ollama which allows specifying a selected model. If this optional parameter is not set, it will behave exactly the same as before: It would use the one specivied with WithDefaultModel on the Ollama resource.

```diff
+ public static IResourceBuilder<T> WithReference<T>(this IResourceBuilder<T> builder, IResourceBuilder<OllamaResource> ollama, string? selectedModel = null ) where T : IResourceWithEnvironment
- public static IResourceBuilder<T> WithReference<T>(this IResourceBuilder<T> builder, IResourceBuilder<OllamaResource> ollama) where T : IResourceWithEnvironment
```

### Usage example

```csharp
var ollama = builder.AddOllama("ollama", port: null)
    .AddModel("phi")
    .AddModel("phi3")
    .WithDefaultModel("phi")
    .WithOpenWebUI();

builder.AddProject<Projects.Aspire_CommunityToolkit_Hosting_Ollama_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(ollama, /* adding this */ "phi3");
``` 

### Breaking change?

No

there is no release yet (also this only adds an optional parameter to an existing method)

### Alternatives

Setting the environment variable (Aspire__OllamaSharp__{resource.Name}__SelectedModel) manually, but that is not easily discoverable without looking at this source code. Maybe the way currently in the playground was added with the intention to do this, but it does not work:
```csharp
builder.AddProject<Projects.Aspire_CommunityToolkit_Hosting_Ollama_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(ollama)
    .WithEnvironment("ollama:model", "phi3");
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
Thinking about this, and also the stuff in #107 there's probably a bit of overhaul that should be done to this integration and how it works in the Aspire app model.

From an API design the `WithReference` requiring a second argument doesn't really align with Aspire, what would be more aligned with the design would be for the `AddModel` to return an `OllamaModelResource` so you could write something like this:

```csharp
var ollama = builder.AddOllama("ollama");

var phi3 = ollama.AddModel("phi3"); // model name is inferred from resource name
var nomic = ollama.AddModel("embedding", "nomic-embed-text"); // model name is explicit

builder.AddProject<Projects.Api>("api")
  .WithReference(phi3)
  .WithReference(nomic);
```

Then in your client you would use `builder.AddOllamaClientApi("phi3");` or `builder.AddOllamaClientApi("embedding");` and that would resolve a different selected/default model.

What's your thoughts on that @Mrxx99?

**Comment by Mrxx99** [comment]
Agree that makes more sense and would also match how it works for databases. Will start working on this
