### ISSUE TITLE
`Aspire.CommunityToolkit.*` -> `CommunityToolkit.Aspire.*`

### ISSUE THREAD

**Issue by aaronpowell** [CommunityToolkit/Aspire#124]
To ensure that we're meeting the governance requirements properly within the Community Toolkit space we need to flip the namespace around.

This will also ensure that we don't hit any problems in the future around ownership.

/cc @michael-hawker

**Comment by ErikEJ** [comment]
@aaronpowell hoping this will not affect VS visibility?

**Comment by aaronpowell** [comment]
> [@aaronpowell](https://github.com/aaronpowell) hoping this will not affect VS visibility?

Do you mean via the `Add Aspire Integration` menu item? That's not reliant on the package naming (still have to work out with the tooling team how we'll get there)

**Comment by michael-hawker** [comment]
Thanks @aaronpowell for the chat and discussion on this space. Took some notes on the history/reasoning here for our list of items to ensure we document in central governance: https://github.com/orgs/CommunityToolkit/projects/11/views/1
