### ISSUE TITLE
There are no versions available for the package 'Aspire.CommunityToolkit.Hosting.Ollama'.

### ISSUE THREAD

**Issue by isaacrlevin** [CommunityToolkit/Aspire#126]
### Describe the bug

Maybe I am missing something but when I try to add the Ollama package via the cli I get this error message. I also do not see it in Nuget Package Manager

> dotnet add package Aspire.CommunityToolkit.Hosting.Ollama
Build succeeded in 0.8s
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Aspire.CommunityToolkit.Hosting.Ollama' into project 'E:\dev\Temp\AspireApp2\AspireApp2.AppHost\AspireApp2.AppHost.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/aspire.communitytoolkit.hosting.ollama/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/aspire.communitytoolkit.hosting.ollama/index.json 248ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/aspire.communitytoolkit.hosting.ollama/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/aspire.communitytoolkit.hosting.ollama/index.json 104ms
error: There are no versions available for the package 'Aspire.CommunityToolkit.Hosting.Ollama'.

### Steps to reproduce

New Aspire Starter App (.NET 8)
try to add Aspire.CommunityToolkit.Hosting.Ollama

### Expected behavior

Nuget package should download

### IDE and version

VS 2022 Preview

### IDE version

17.12.0 Preview 3

### Nuget packages

- [ ] Aspire.CommunityToolkit.Hosting.Azure.StaticWebApps
- [ ] Aspire.CommunityToolkit.Hosting.Java
- [ ] Aspire.CommunityToolkit.Hosting.NodeJS.Extensions
- [x] Aspire.CommunityToolkit.Hosting.Ollama

### Nuget package version(s)

N/A

### Help us help you

Yes, but only if others can assist

**Comment by aaronpowell** [comment]
The packages aren't yet on nuget.org, we're tracking that with #48. We're aiming to have them on NuGet soon 🤞.

You can access the packages via our Azure Artifacts feed (we added that yesterday via #120).

Also, I've moved the packages to `CommunityToolkit.Aspire.*` (see #124) so make sure you grab the one named that from the Azure Artifact feed.

**Comment by aaronpowell** [comment]
Yes, it's a design limitation with how optional arguments are handled in C# with regards to overloads.

The Ollama integration was originally provided by the folks at Raygun from [their integration](https://github.com/MindscapeHQ/Raygun.Aspire.Hosting.Ollama) and to ensure API compatibility on the initial release we had to have the overload with three arguments, but to align with the Aspire API design we moved to the one without a `modelName` argument and instead use the `WithModel` method. The deprecated method will be removed with the Aspire 9 release.

To avoid the issue today, you can do `builder.AddOllama("ollama", port: null)` which is what we do [in our example](https://github.com/CommunityToolkit/Aspire/blob/main/examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.AppHost/Program.cs#L3).

Also, the package is now on NuGet - https://www.nuget.org/packages/CommunityToolkit.Aspire.Hosting.Ollama/
