### ISSUE TITLE
Add meilisearch-ui for meilisearch

### ISSUE THREAD

**Issue by Alirexaa** [CommunityToolkit/Aspire#128]
### Overview

 Add https://github.com/riccox/meilisearch-ui as the UI dashboard for meilisearch.

### Usage example

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var meilisearch = builder.AddMeilisearch("meilisearch")
                         .WithMeilisearchUI();
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Alirexaa** [comment]
I prepared a PR but there is an issue in Meilisearch UI when using it in singleton mode.
See https://github.com/riccox/meilisearch-ui/issues/165

**Comment by aaronpowell** [comment]
Does that bug mean we're blocked on getting this integration added?

**Comment by aaronpowell** [comment]
Shall we close this? Seems like they bug isn't going to have a resolution so we'll be permanently blocked.
