### ISSUE TITLE
Verify `ExecutionContext` is needed in all Node.js extensions

### ISSUE THREAD

**Issue by aaronpowell** [CommunityToolkit/Aspire#153]
> I looked at Node.js extensions and did not see any checking about that ExecuationContext being in run mode. It seems we have an issue with that right now. If we use these extensions only in development, we should have to check that ExecuationContext is in run mode.
> And I think it's better to change AddViteApp to WithRunViteApp.
> 
> That's a very good point, I'll add an issue tracking it. 

 _Originally posted by @aaronpowell in [#115](https://github.com/CommunityToolkit/Aspire/issues/115#issuecomment-2434338681)_

**Comment by Alirexaa** [comment]
Do we have the same issue for `CommunityToolkit.Aspire.Hosting.Deno`?

**Comment by aaronpowell** [comment]
Probably. Deno should deploy as a container IMO

**Comment by aaronpowell** [comment]
Having a look into this issue and the way that we have it done at the moment is how it seem to work for the Node.js integration that is part of the Aspire core.

Taking https://learn.microsoft.com/dotnet/aspire/get-started/build-aspire-apps-with-nodejs as our guide (well, the [samples repo](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithJavaScript)) we can note that they always include the `.PublishAsDockerFile` method at the end of the chain.

This results in the following JSON in the manifest:

```json
    "angular": {
      "type": "dockerfile.v0",
      "path": "AspireJavaScript.Angular/Dockerfile",
      "context": "AspireJavaScript.Angular",
      "env": {
        "NODE_ENV": "development",
        "services__weatherapi__http__0": "{weatherapi.bindings.http.url}",
        "services__weatherapi__https__0": "{weatherapi.bindings.https.url}",
        "PORT": "{angular.bindings.http.targetPort}"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 8000,
          "external": true
        }
      }
    }
```

If we remove any publishing instructions we get this:

```json
    "angular": {
      "type": "executable.v0",
      "workingDirectory": "AspireJavaScript.Angular",
      "command": "npm",
      "args": [
        "run",
        "start"
      ],
      "env": {
        "NODE_ENV": "development",
        "services__weatherapi__http__0": "{weatherapi.bindings.http.url}",
        "services__weatherapi__https__0": "{weatherapi.bindings.https.url}",
        "PORT": "{angular.bindings.http.targetPort}"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 8000,
          "external": true
        }
      }
    }
```

And this is the same as we get out of our samples.

Because of this, I don't think there's really anything "special" we should be doing in our extensions (or integrations in the case of Deno) to handle the different execution modes. Probably the only real consideration would be the `NpmPackageInstallerLifecycleHook` (and similar hooks) which are doing a check for whether it's in publish mode or not and if it is, skipping the logic.

Is there anything specific you think we should add @Alirexaa for handling publish vs run mode in these?

**Comment by Alirexaa** [comment]
@aaronpowell, Thanks for this research.
Skiping the logic in publish mode is good enough.
