### ISSUE TITLE
Add code coverage for items below min rate

### ISSUE THREAD

**Issue by Alirexaa** [CommunityToolkit/Aspire#168]
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-80%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder | 100% | 100% | 6 | ✔
CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps | 100% | 100% | 28 | ✔
CommunityToolkit.Aspire.Hosting.Deno | 84% | 75% | 72 | ✔
CommunityToolkit.Aspire.Hosting.Golang | 94% | 50% | 16 | ✔
CommunityToolkit.Aspire.Hosting.Java | 98% | 71% | 58 | ✔
CommunityToolkit.Aspire.Hosting.Meilisearch | 61% | 27% | 94 | ➖
CommunityToolkit.Aspire.Hosting.NodeJS.Extensions | 90% | 68% | 92 | ✔
CommunityToolkit.Aspire.Hosting.Ollama | 52% | 33% | 180 | ❌
CommunityToolkit.Aspire.Meilisearch | 97% | 92% | 68 | ✔
CommunityToolkit.Aspire.OllamaSharp | 95% | 83% | 90 | ✔
**Summary** | **80%** (1202 / 1498) | **57%** (308 / 536) | **704** | ✔

_Minimum allowed line rate is `60%`_

**Comment by aaronpowell** [comment]
Loking at what we're getting from the reports, a lot of where our coverage is low are in projects that we really shouldn't be worried about, such as the AppHost projects and I've noticed that DAB is also having coverage triggered on the Blazor app.

I think we should add an assembly filter like this:

```yaml
    assemblyfilters: *.AppHost;CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder.BlazorApp;*.ServiceDefaults;CommunityToolkit.Aspire.Testing
```

That way we can have the coverage focusing on the stuff in the `src/` folder properly.

**Comment by aaronpowell** [comment]
I'm going to close this - we've hit the minimum bar on all integrations now
