### ISSUE TITLE
Golang fixed PORT

### ISSUE THREAD

**Issue by tommasodotNET** [CommunityToolkit/Aspire#209]
### Describe the bug

Golang PORT should not be fixed to a user hardcoded by the user, but Aspire should be able to randomly assign one using a custom env PORT.

### Steps to reproduce

```text
Currently user can only assign a PORT manually when calling `AddGolangApp()` and that needs to match the PORT to which the server is listening on.
```

### Expected behavior

User should be able to not choose a PORT value and let Aspire assign one.

### IDE and version

Other

### Nuget packages

- [ ] CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder
- [ ] CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps
- [ ] CommunityToolkit.Aspire.Hosting.Deno
- [x] CommunityToolkit.Aspire.Hosting.Golang
- [ ] CommunityToolkit.Aspire.Hosting.Java
- [ ] CommunityToolkit.Aspire.Hosting.Meilisearch
- [ ] CommunityToolkit.Aspire.Hosting.NodeJS.Extensions
- [ ] CommunityToolkit.Aspire.Hosting.Ollama
- [ ] CommunityToolkit.Aspire.Meilisearch
- [ ] CommunityToolkit.Aspire.OllamaSharp

### Nuget package version(s)

9.0.0-beta.54

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by tommasodotNET** [comment]
@aaronpowell we have two ways to handle this. Either we DO NOT configure http endpoint in the extension and let the user configure that when calling AddGolangApp(), or we configure it as
```csharp
.WithHttpEndpoint(env: "PORT", name: GolangAppExecutableResource.HttpEndpointName)
```

Which one seems better?

**Comment by aaronpowell** [comment]
It shouldn't be on the `AddGolangApp` method as the port is only valid/used when you specify that you want a HTTP/HTTPS endpoint

**Comment by tommasodotNET** [comment]
We might have the same issue in the [NodeJs extensions](https://github.com/CommunityToolkit/Aspire/blob/main/src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs)

**Comment by aaronpowell** [comment]
I don't think so, only the Vite support sets a port but it does that by adding an endpoint

**Comment by tommasodotNET** [comment]
Kinda confused on this. In Golang we demand to the AppHost the task to use the `WithHttpEndpoint(env: "PORT")`, but in Vite we have the `WithHttpEndpoint(env: "PORT")` inside the `AddViteApp()` method. Isn't this inconsistent as a behaviour?
