### ISSUE TITLE
ReadMe hosting links are not working at the moment

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [CommunityToolkit/Aspire#226]
### Page URL

readme.md

### Describe the issue

Hosting.Rust etc. links are not working. Actual link for Rust is is https://learn.microsoft.com/dotnet/aspire/community-toolkit/hosting-rust

### Suggestion

I have no suggestion

### Help us help you

No, just wanted to report this

**Comment by Alirexaa** [comment]
@zahirtezcan-bugs thanks for your report.
Docs will be added for these links soon.

**Comment by aaronpowell** [comment]
Docs have been published, so I'll go ahead and close this now.
