### ISSUE TITLE
Container created WithOpenWebUI does not receive environment variables

### ISSUE THREAD

**Issue by JohnMidity** [CommunityToolkit/Aspire#241]
### Describe the bug

Environment variables added using `WithEnvironment()` are provided to the main Ollama container, but not to the OpenWebUI container that is added with `WithOpenWebUi()`.

### Steps to reproduce

```text
Environment: .Net 9
Packages:

<PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
<PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="8.3.0" />


1. Create a new ASP.Net project with Aspire support and add this to program.cs
 csharp
var ollama = builder.AddOllama("ollama")
                    .AddModel("llama3")
                    .WithOpenWebUI()
                    .WithDataVolume()
                    .WithLifetime(ContainerLifetime.Persistent)
                    .WithEnvironment("DCP_IDE_REQUEST_TIMEOUT_SECONDS", "600");


2. Start the application.
3. In the Aspire dashboard, review the environment variables in the details of `ollama-openwebui` container. Observe missing variable `DCP_IDE_REQUEST_TIMEOUT_SECONDS`. For comparison, the variable will be present in the `ollama` container.
```

### Expected behavior

Environment variable should be added to both containers.

### IDE and version

VS 2022

### IDE version

17.12.0

### Nuget packages

- [ ] CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder
- [ ] CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps
- [ ] CommunityToolkit.Aspire.Hosting.Deno
- [ ] CommunityToolkit.Aspire.Hosting.Golang
- [ ] CommunityToolkit.Aspire.Hosting.Java
- [ ] CommunityToolkit.Aspire.Hosting.Meilisearch
- [ ] CommunityToolkit.Aspire.Hosting.NodeJS.Extensions
- [x] CommunityToolkit.Aspire.Hosting.Ollama
- [ ] CommunityToolkit.Aspire.Meilisearch
- [ ] CommunityToolkit.Aspire.OllamaSharp

### Nuget package version(s)

8.3.0, 28 October 2024

### Help us help you

No, just wanted to report this

**Comment by Alirexaa** [comment]
The `WithOpenWebUI()` returns an instance of `IResourceBuilder<OllamaResource>` so any chanid extension method will configure the `OllamaResource` not `OpenWebUIResource`.

Instead, you should use the `configureContainer` parameter of `WithOpenWebUI`:

```csharp
var ollama = builder.AddOllama("ollama")
    .WithDataVolume()
    .WithOpenWebUI(c =>
    {
        //configure open web ui here
        c.WithEnvironment("DCP_IDE_REQUEST_TIMEOUT_SECONDS", "600");
    });
```

**Comment by JohnMidity** [comment]
Sorry, I overlooked that. That does indeed work.
Thank you for your quick response @Alirexaa
