### ISSUE TITLE
[Feature] Add ActiveMQ hosting

### ISSUE THREAD

**Issue by anoordover** [CommunityToolkit/Aspire#253]
We should migrate the ActiveMQ hosting from this PR (https://github.com/dotnet/aspire/pull/4094) to the CommunityToolkit.

Minimal requirements:
- The protocol should be configurable (https://masstransit.io/ expects a protocol activemq when using a connection-string)

**Comment by anoordover** [comment]
@aaronpowell I'm trying to move the project from the dotnet aspire repository to this repository.
To generate a volume-name I use the VolumeNameGenerator class. Am I allowed to use this class from the shared-folder in this project or should I aim for another solution?

**Comment by Alirexaa** [comment]
> [@aaronpowell](https://github.com/aaronpowell) I'm trying to move the project from the dotnet aspire repository to this repository. To generate a volume-name I use the VolumeNameGenerator class. Am I allowed to use this class from the shared-folder in this project or should I aim for another solution?

Yes, there is an example for meiliesearch.

https://github.com/CommunityToolkit/Aspire/blob/02802ac98f717c4881f989176f33d61cbbe97c4e/src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj#L11
