### ISSUE TITLE
[Feature] Add Structurizr support for .NET Aspire

### ISSUE THREAD

**Issue by shahabganji** [CommunityToolkit/Aspire#257]
### .NET Aspire issue link

https://github.com/dotnet/aspire/pull/4680

### Overview

[Structurizr](https://structurizr.com/) is a tool which builds upon "diagrams as code", allowing you to create multiple software architecture diagrams from a single model. The diagrams and documentations created as [C4](https://c4model.com/) model and ADRs respectively. By adding the Aspire support, it makes the addition of this resource to the projects straight forward and helps developers to integrate this approach easily on their projects.

### Usage example

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddStructurizr("structurizr");

builder.Build().Run();
```
--- 

```csharp

var builder = DistributedApplication.CreateBuilder(args);

builder.AddStructurizr("structurizr", 9090);

builder.Build().Run();
```

--- 

```csharp

var builder = DistributedApplication.CreateBuilder(args);

var path = Path.Combine(Directory.GetCurrentDirectory(), "..", "architecture");
builder.AddStructurizr("structurizr", bindPath: path);

builder.Build().Run();
```

--- 

```csharp

var builder = DistributedApplication.CreateBuilder(args);

builder.AddStructurizr("structurizr", 9090, Environment.CurrentDirectory);

builder.Build().Run();
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
I'm unfamiliar with this tool, but having a read of the docs, I'm not sure I understand the role that this would play in an applications architecture - what would the resource provide to other resources in the application?

**Comment by aaronpowell** [comment]
As I look more into this, I'm of the opinion that it's not the right thing for the Community Toolkit to adopt.

While I can see where this could fit into the overall repository for an application, that consists of source code, tests, infrastructure definitions, and documentation, it doesn't fit into the model of Aspire when it comes to managing the orchestration of a distributed application.
