### ISSUE TITLE
Hosting & client package for masstransit rabbitmq

### ISSUE THREAD

**Issue by MichielBrys** [CommunityToolkit/Aspire#275]
I already made this package which is currently on nuget, I thought it might be a good fit for the communitytoolkit. 

https://www.nuget.org/packages/AspireMassTransit.RabbitMQ.Client 
https://www.nuget.org/packages/AspireMassTransit.RabbitMQ.Hosting 

Just making this issue like mentioned in the contribution guide before making a pull request.

Thanks!

**Comment by aaronpowell** [comment]
If you'd like to contribute these to the Community Toolkit @MichielBrys then we'd be happy to help onboard them (and we can add you as the CODEOWNER if you're able/interested in continuing to own them).

**Comment by aaronpowell** [comment]
This would be a good companion with #253 (assuming I understand how all these parts come together - messaging platforms aren't my area 😅)

**Comment by MichielBrys** [comment]
I'd love to contribute these to the community toolkit, being added as the codeowner would be nice aswell! I'll setup up a pull request somewhere today after reading through the guidelines so I don't get code reviewed to hell. Thanks!

The issue you linked is indeed quite similar, both using masstransit but a different underlying messaging service, so they can be grouped a bit :)

**Comment by anoordover** [comment]
+1

**Comment by davidfowl** [comment]
This had the same sort of tentacles from a complexity pov as entity framework. We should make sure there’s real value in doing this vs doing something natively in mass transit

**Comment by aaronpowell** [comment]
> This had the same sort of tentacles from a complexity pov as entity framework. We should make sure there’s real value in doing this vs doing something natively in mass transit

Do you mean because this would result in only a package supporting RabbitMQ but not, say Azure Service Bus or Amazon SQS, leaving some gaps in the integration coverage?

**Comment by davidfowl** [comment]
It’s any framework that has a provider model could result in an integration matrix explosion. You’re taking on the burden of maintaining provider + framework packages. We do this with entity framework and database provider and asp.net core’s various caching models.

**Comment by aaronpowell** [comment]
That's an inherent aspect of Aspire though, it's a provider model itself and someone is going to take on the burden of maintaining the integrations.

**Comment by davidfowl** [comment]
We’re not using provider model in the same way here. Aspire integrations are not a provider model the same way EF has for EF providers or mass transit has for transports. That’s what I’m talking about with this issue.

Adding aspire to an existing provider model should be do with care and is best done closest to the owner of the provider model (or someone with a deep understanding of the implications of entering that space).

**Comment by aaronpowell** [comment]
Preview packages are available on NuGet
