### ISSUE TITLE
Error page when starting CommunityToolkit.Aspire.Hosting.Ollama.AppHost

### ISSUE THREAD

**Issue by anoordover** [CommunityToolkit/Aspire#294]
### Describe the bug

When I go to the web-project after starting CommunityToolkit.Aspire.Hosting.Ollama.AppHost I get an error page with the title:
InvalidOperationException: Cannot provide a value for property 'OllamaClient1' on type 'CommunityToolkit.Aspire.Hosting.Ollama.Web.Components.Pages.Home'. There is no registered keyed service of type 'Microsoft.Extensions.AI.IChatClient' with key 'phi3'.

### Steps to reproduce

```text
1. start CommunityToolkit.Aspire.Hosting.Ollama.AppHost
2. go to the web-project using the link in the AppHost
```

### Expected behavior

I wouldn't expect this error to show up.

### Screenshots

![Image](https://github.com/user-attachments/assets/c2942d8f-c872-4a18-b6bd-6f2e2c864861)

### IDE and version

Rider

### IDE version

2024.3

### Nuget packages

```text

```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by anoordover** [comment]
Should we change the lines

builder.AddKeyedOllamaApiClient(ServiceKeys.Phi3);
builder.AddKeyedOllamaApiClient(ServiceKeys.Llama);

to

builder.AddKeyedOllamaSharpChatClient(ServiceKeys.Phi3);
builder.AddKeyedOllamaSharpChatClient(ServiceKeys.Llama);

in the program.cs class in the Ollama.Web project?

**Comment by aaronpowell** [comment]
Ah good catch. Yes, it should be using the second registration. I must have messed that up in a refactor.
