### ISSUE TITLE
External Web API as an resource

### ISSUE THREAD

**Issue by luizfbicalho** [CommunityToolkit/Aspire#312]
### Overview

 couldn't find any extension or package for this, so I'll just show some code as an example.

In one project, I have more than 10 external APIs, if those external APIs were .NET projects in my solution, I would add them as project references in my Aspire main project.

For example this is my web project:

```cs
builder.AddProject<Projects.Main_Web>("web")
    .WithReference(connectionStringHangfire)
    .WithHttpsHealthCheck("/health")
    .WithExternalHttpEndpoints()
    .WaitForCompletion(migrations);
```
And for example I should have an external API for stock quotes

```cs
builder.AddExternalApi<IStock>("stock")
    .WithHttpsHealthCheck("/health",r=>r.Health() ); // added one of the APIs as a health check
```

### Usage example

This way I could monitor the stock API in my resources tab, I should see what its health is, I could add the health check of the API to my health check.

I could control the base url, user, client-id, password, as parameters to my environment

I could control the log, trace an metrics of those APIs.

And finally, I could add reverse proxy around it, or vpn, around it.

### Help us help you

Maybe, not sure if I can help but I could try

**Comment by aaronpowell** [comment]
I feel like I saw some discussion on this recently - @davidfowl does this ring any bells, or is it something the Aspire team has looked into?

**Comment by davidfowl** [comment]
This one will be built into aspire itself

**Comment by luizfbicalho** [comment]
> This one will be built into aspire itself

Nice, is there already an issue that I can follow?

**Comment by davidfowl** [comment]
There are 2:

https://github.com/dotnet/aspire/issues/3108
https://github.com/dotnet/aspire/issues/2311

**Comment by wertzui** [comment]
I haven't (yet) tested them with health checks, but I have made a small NuGet package which adds External endpoints as resource, so they can be consumed via Service discovery:
https://github.com/wertzui/Aspire.Hosting.ExternalEndpoint
https://www.nuget.org/packages/ExternalEndpoint.Aspire.Hosting/

**Comment by aaronpowell** [comment]
I'm going to close this as it'll be part of Aspire so it'd be best to take the discussions over to their repo and engage with the current open issues.
