### ISSUE TITLE
HomeAssistant hosting integration

### ISSUE THREAD

**Issue by IEvangelist** [CommunityToolkit/Aspire#325]
### Overview

I'm new to [HomeAssistant](https://www.home-assistant.io/), but I learned that they have a container image available - and that most folks use docker compose, this led me to immediately think that we should expose this as a community .NET Aspire hosting integration. I'd love to have HomeAssistant available as a hosting integration, so community members can quickly benefit from it as well.

### Usage example

```
var builder = DistributedApplication.CreateBuilder(args);

builder.AddHomeAssistant("home-assistant")
       .WithDataVolume()
       .WithLifetime(ContainerLifetime.Persistent);

builder.Build().Run();
```

### Additional context

.NET Aspire dashbaord:

![Image](https://github.com/user-attachments/assets/697f224f-6e7e-4fd4-8ee4-200a3d645c9c)

HomeAssistant welcome page:

![Image](https://github.com/user-attachments/assets/f8ffd4a4-f9c2-47e0-b835-dd2a6ddd6602)

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
I'm not sure I understand what value is being gained by having Aspire in the mix here, is it just to avoid having to write a Docker Compose file? Would you be providing the resource as a reference to other resources, or consuming resources into HA? My instinct is that this wouldn't be a particularly useful integration broadly in the Aspire community.

As an aside - I'm a HA user myself and I'd discourage using it as a container and instead use HA OS as the install type, either running it on a Pi or in a VM (on something like VirtualBox or, in my case, Proxmox). Running in a container means you lose access to add-ons and backups are a bit harder to handle.

**Comment by aaronpowell** [comment]
@IEvangelist see👆

**Comment by IEvangelist** [comment]
Yeah, if you don't think it's useful - I'm fine with that. I'm new to HA, so at first it felt like an opportunity to include with Aspire.

**Comment by 3GDXC** [comment]
Home Assistant and .NET integrations I feel is a good development; the experiance and setup for the developer is somewhat complex with a number of component services required; a distrubute application such as Home Assistant and https://github.com/leosperry/ha-kafka-net would greatly benefit from using aspire as the local orchestrator with features such as hot reload and the aspire dashboard enhancing the developer inner loop.
