### ISSUE TITLE
Pre predeployment script support for SQL Projects

### ISSUE THREAD

**Issue by ErikEJ** [CommunityToolkit/Aspire#331]
### Related to an existing integration?

Yes

### Existing integration

CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects

### Overview

In our workflow we often have to resort having a [pre predeployment script](https://learn.microsoft.com/en-us/archive/blogs/gertd/pre-deployment-scripts) as described the archutect behind SSDT. We have destructive actions in this script for example.

Having the ability to point to this script and having it run against the database if it exists would be a great addition to this integration, particular for keeping the database persisted between invocations.

The script is assumed to be authored as idempotent, and the integration schould only execute the script if the database exists.

@jmezach FYI!

### Usage example

var builder = DistributedApplication.CreateBuilder(args);

var sql = builder.AddSqlServer("sql")
                 .AddDatabase("test");

builder.AddSqlProject<Projects.MySqlProj>("mysqlproj")
      .WithPreScript("path/to/script.sql")
       .WithReference(sql);

### Breaking change?

No

### Alternatives

Not aware of any other integrations that can do this, but I could easily be wrong

### Help us help you

Yes, but only if others can assist

**Comment by jmezach** [comment]
@ErikEJ I guess it should be fairly easy to run a script before deploying the `.dacpac` by creating a `SqlCommand` and putting in the script, but there's a couple of challenges that I can think of:

- With Aspire the database creation is usually done under the hood of the `.dacpac` deployment, so if we run a script before that the database might not yet exist. This may or may not be a problem depending on whether the pre pre-script does something to the database
- If the pre pre-script needs to leverage any SQLCMD variables we might be in for a challenge as we'd need to have some mechanism that can parse the script and replace those variables. Maybe the DacFx library provides something for that, but I'm not sure.

**Comment by ErikEJ** [comment]
@jmezach 

For us, having the pre pre script is only relevant if the database is persisted between invocations of the App Host.

We assume the script executes against the user database.

We have statements similar to this in it:

```sql
IF OBJECT_ID('dbo.WorkflowProcess', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.WorkflowProcess
END
```

We have no need for sqlcmd variables or GO statements.

The only issue I can see is that the script will fail on first run if the database does not exist, but for that we could add a database existance check, using the supplied connection string and a simple `SqlConnection.Open(SqlConnectionOverrides.OpenWithoutRetry) `to fail fast.

**Comment by aaronpowell** [comment]
Why would this be done as part of the app host and not in the referenced SQL project? My impression was that that project was responsible for configuring the server with all the required databases/tables/etc. so what's the pre deployment script for?

**Comment by ErikEJ** [comment]
@aaronpowell If you do not want destructive actions in your database project, you need the pre predeploy script, as described in the link from the old blog post by Geert Drapers above.

And as mentioned above, this is only needed if the database is on a persisted volume/disk.

Having the pre -predeploy script executed allows the developer to verify/test this early.

Hope this makes sense?

**Comment by ErikEJ** [comment]
I will just use this approach, it will fullfill our requirements:

https://github.com/dotnet/aspire-samples/blob/main/samples/DatabaseContainers/DatabaseContainers.AppHost/Program.cs#L37

**Comment by ErikEJ** [comment]
(Would be nice if this was simpler, though)

**Comment by ErikEJ** [comment]
Maybe this is a feature request to the authors of the SQL Server image? (Looking at the comments for the other db containers in the link above)
