### ISSUE TITLE
Data Api Builder (DAB)

### ISSUE THREAD

**Issue by FBoucher** [CommunityToolkit/Aspire#39]
### Overview

Add a reference to a API geenrated by the [Data API Builder](https://github.com/Azure/data-api-builder) by passing the configuration file. The API will be in a container.

```csharp
var dab = builder.AddDataAPIBuilder("./dab-config.json");

builder.AddProject<Projects.mywebsite>("mywebsite")
    .WithExternalHttpEndpoints()
    .WithReference(dab);
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
Merged with the aspire-9 branch
