### ISSUE TITLE
Azure API Management

### ISSUE THREAD

**Issue by justinyoo** [CommunityToolkit/Aspire#59]
### .NET Aspire issue link

https://github.com/dotnet/aspire/issues/2235

### Overview

The use of Azure API Management (APIM) is common in many integration scenarios. However, it's not yet natively supported by .NET Aspire. It would be great that we support this APIM integration.

### Usage example

In the `AppHost` project:

```csharp
var apim = builder.AddAzureApiManagement(
    "myapim",
    new AzureApiManagementOptions()
    {
        BaseUrl = "https://my-apim.azure-api.net/api",
        SubscriptionKey = "{{this-is-subscription-key}}"
    });

builder.AddProject<Projects.My_Aspire_WebApp>("webapp")
       .WithReference(apim);

```

In the consuming project:

```csharp
builder.Services.AddHttpClient<IApimClient, ApimClient>(client
    => client.BaseAddress = new Uri("https+http://apim"));
```

### Additional context

- I'd like to get myself assigned. But before that, I'd also like to discuss its feasibility first.
- I'm not sure how OpenTelemetry related data is propagated from one app to the other through APIM.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
Going to close this as it's not something we'll build at the moment.
